# Generated by Django 4.2.11 on 2025-03-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainee_images/'),
        ),
    ]
