# Generated by Django 4.2.11 on 2025-03-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_start_date_remove_course_title_and_more'),
        ('trainee', '0002_trainee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='image',
        ),
        migrations.AddField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
