# Generated by Django 4.2.11 on 2025-03-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_remove_trainee_age_remove_trainee_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainee_images/'),
        ),
    ]
