# Generated by Django 4.2.11 on 2025-03-15 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_start_date_remove_course_title_and_more'),
        ('trainee', '0004_trainee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='image',
        ),
        migrations.AddField(
            model_name='trainee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
